#!/bin/busybox sh

busybox mount -t devtmpfs  devtmpfs  /dev
busybox mount -t proc      proc      /proc
busybox mount -t sysfs     sysfs     /sys
busybox mount -t tmpfs     tmpfs     /tmp

busybox sh
